extends Node

signal PLAYER_DIED;
signal PLAYER_TOUCHED_CUP;
signal LOAD_NEXT_AREA;
signal RESET_PLAYER_POSITION;
signal PLAYER_TOUCHED_CHECKPOINT;
signal PLAYER_LIVES_UPDATED;
signal PLAYER_POSITION_RESET_DONE;
signal PLAYER_FINISHED_DISAPPEARING;
